### ISSUE TITLE
Bar: keep shape

### ISSUE THREAD

**Issue by Doidel** [nagix/chartjs-plugin-rough#2]
Hello @nagix, thanks for this great plugin.
Is it possible to keep the shape of the bar on hover? Currently, it changes / reinitializes on every mousemove. Can we prevent that somehow?

**Comment by nagix** [comment]
If you don't need the tooltip/hover animations on mousemove, this option disables the update ([reference](https://www.chartjs.org/docs/latest/general/interactions/events.html#event-option)):

```js
options: {
    events: ['click']
}
```

**Comment by Doidel** [comment]
Oh great, yeah I don't, that solves it for me. Many thanks!
